<?xml version="1.0" encoding="UTF-8" ?>
<archetype>
	<name>${artifactId}</name>
	<source>
		<path>pom.xml</path>
		<template>pom.ftl</template>
	</source>
	<module>
		<name>${artifactId}-common</name>
		<source>
			<path>pom.xml</path>
			<template>common/pom.ftl</template>
		</source>
		<source>
			<path>src/main/java/${basePackage?replace(".","/")}/common/App.java</path>
			<template>common/app.ftl</template>
		</source>
		<source>
			<path>src/test/java/${basePackage?replace(".","/")}/common/AppTest.java</path>
			<template>common/AppTest.ftl</template>
		</source>
	</module>
	<module>
		<name>${artifactId}-data</name>
		<source>
			<path>pom.xml</path>
			<template>data/pom.ftl</template>
		</source>
		<source>
			<path>src/test/java/${basePackage?replace(".","/")}/data/AppTest.java</path>
			<template>data/AppTest.ftl</template>
		</source>
		<#list entities as e>
		<source>
			<path>src/main/java/${basePackage?replace(".","/")}/data/${e.moduleName}/I${e.entityName}Dao.java</path>
			<template>data/idao.ftl</template>
			<entity>${e.entityName}</entity>
		</source>
		<source>
			<path>src/main/java/${basePackage?replace(".","/")}/data/${e.moduleName}/entity/${e.entityName}.java</path>
			<template>data/entity.ftl</template>
			<entity>${e.entityName}</entity>
		</source>
		<source>
			<path>src/main/java/${basePackage?replace(".","/")}/data/${e.moduleName}/impl/${e.entityName}DaoImpl.java</path>
			<template>data/daoimpl.ftl</template>
			<entity>${e.entityName}</entity>
		</source>
		<source>
			<path>src/main/resources/${basePackage?replace(".","/")}/data/${e.moduleName}/impl/${e.entityName}DaoImpl.sql.xml</path>
			<template>data/sql.xml.ftl</template>
            <entity>${e.entityName}</entity>
		</source>
		</#list>
	</module>
	<module>
		<name>${artifactId}-service</name>
		<source>
			<path>pom.xml</path>
			<template>service/pom.ftl</template>
		</source>
		<source>
			<path>src/test/java/${basePackage?replace(".","/")}/service/AppTest.java</path>
			<template>service/AppTest.ftl</template>
		</source>
		<#list entities as e>
		<source>
			<path>src/main/java/${basePackage?replace(".","/")}/service/${e.moduleName}/dto/${e.entityName}DTO.java</path>
			<template>service/dto.ftl</template>
			<entity>${e.entityName}</entity>
		</source>
		<source>
			<path>src/main/java/${basePackage?replace(".","/")}/service/${e.moduleName}/I${e.entityName}Service.java</path>
			<template>service/iservice.ftl</template>
			<entity>${e.entityName}</entity>
		</source>
		<source>
			<path>src/main/java/${basePackage?replace(".","/")}/service/${e.moduleName}/impl/${e.entityName}ServiceImpl.java</path>
			<template>service/serviceimpl.ftl</template>
			<entity>${e.entityName}</entity>
		</source>
		</#list>
	</module>
	<module>
		<name>${artifactId}-control</name>
		<source>
			<path>pom.xml</path>
			<template>control/pom.ftl</template>
		</source>
		<source>
			<path>src/test/java/${basePackage?replace(".","/")}/control/AppTest.java</path>
			<template>control/AppTest.ftl</template>
		</source>
		<#list entities as e>
		<source>
			<path>src/main/java/${basePackage?replace(".","/")}/control/${e.moduleName}/${e.entityName}Controller.java</path>
			<template>control/controller.ftl</template>
			<entity>${e.entityName}</entity>
		</source>
		</#list>
	</module>
	
	<module>
		<name>${artifactId}-web</name>
		<source>
			<path>pom.xml</path>
			<template>web/pom.ftl</template>
		</source>
		<source>
			<path>src/main/resources/logback.xml</path>
			<template>web/logback.xml.ftl</template>
		</source>
		<source>
			<path>src/main/resources/messages_en.properties</path>
			<template>web/messages.properties.ftl</template>
		</source>
		<source>
			<path>src/main/resources/conf/pasp.properties</path>
			<template>web/conf/pasp.properties.ftl</template>
		</source>
		<source>
			<path>src/main/resources/conf/spring/${artifactId}-web.spring.xml</path>
			<template>web/conf/spring/web.spring.xml.ftl</template>
		</source>
		<source>
			<path>src/main/resources/conf/spring/spring-mvc.xml</path>
			<template>web/conf/spring/spring-mvc.xml.ftl</template>
		</source>
		<!-- webapp -->
		<source>
			<path>src/main/webapp/WEB-INF/web.xml</path>
			<template>web/webapp/web.xml.ftl</template>
		</source>
		<source>
			<path>src/main/webapp/index.jsp</path>
			<template>web/webapp/index.jsp.ftl</template>
		</source>
		<source>
			<path>src/main/resources/conf/jdbc.properties</path>
			<template>web/conf/jdbc.properties.ftl</template>
		</source>
	</module>
</archetype>